### ISSUE TITLE
Mike Katz photo not displaying

### ISSUE THREAD

**Issue by obuseme** [raywenderlich/RWDevCon-App#17]
The title says it all. C’mon @sberrevoets !!!

**Comment by DerekSelander** [comment]
Yeah @sberrevoets  c'mon

**Comment by sberrevoets** [comment]
Fixed in 09aa80d7f35ed398ff83b3e8b0317a36b1f60093

We'll have a post-mortem and a retrospective on how such a horrible thing could have slipped past QA.

**Comment by DerekSelander** [comment]
@sberrevoets We are getting pressure from the CEO for increased unit tests so stuff like this doesn't ever happen again

**Comment by sberrevoets** [comment]
Is there a JIRA?

**Comment by crispy8888** [comment]
Clear your schedules for the next week, gentlemen, and we’ll have an all-hands-on meeting with the C-suite on how to improve our processes so we can prevent Ray’s good name from being sullied by such low-quality apps in the future. Sigh. If only I’d been at RWDevCon this year, NONE of this would have happened, I know it...
